2023-12-19 17:55:44,132 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-12-19 17:55:44,133 INFO supervisord started with pid 7
2023-12-19 17:55:45,134 INFO spawned: 'app' with pid 8
2023-12-19 17:55:45,135 INFO spawned: 'nginx' with pid 9
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2023-12-19 17:55:46,320 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-12-19 17:55:46,320 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 19.12.23 17:55:48] [Level: info] id: 20fdbfb1ae19e8a9
[Time: 19.12.23 17:55:48] [Level: info] coordinator: True
[Time: 19.12.23 17:55:48] [Level: info] clients: ['20fdbfb1ae19e8a9']
127.0.0.1 - - [19/Dec/2023 17:55:48] "POST /api/setup HTTP/1.0" 200 0
[Time: 19.12.23 17:55:48] [Level: info] state: initial
[Time: 19.12.23 17:55:48] [Level: info] [State: initial] Reding config file
[Time: 19.12.23 17:55:48] [Level: info] [State: initial] data: lalalaldata100.csv
[Time: 19.12.23 17:55:48] [Level: info] [State: initial] Reading data ...
127.0.0.1 - - [19/Dec/2023 17:55:48] "GET /api/status HTTP/1.0" 200 155
[Time: 19.12.23 17:55:48] [Level: info] Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 251, in guarded_run
    self.run()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 270, in run
    transition = self.current_state.run()
  File "/app/states.py", line 31, in run
    df = pd.read_csv(f'{INPUT_DIR}/{input_file}')
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/root/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'mnt/input/lalalaldata100.csv'

127.0.0.1 - - [19/Dec/2023 17:55:51] "GET /api/status HTTP/1.0" 200 167
