2023-12-07 13:44:36,864 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-12-07 13:44:36,865 INFO supervisord started with pid 7
2023-12-07 13:44:37,870 INFO spawned: 'app' with pid 8
2023-12-07 13:44:37,873 INFO spawned: 'nginx' with pid 9
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 259, in register
    state.register()
  File "/app/states.py", line 18, in register
    self.register_transition(COMPUTE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 570, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 355, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 402, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 07.12.23 13:44:37] [Level: fatal] target state compute not found
2023-12-07 13:44:38,010 WARN exited: app (exit status 1; not expected)
2023-12-07 13:44:39,015 INFO spawned: 'app' with pid 13
2023-12-07 13:44:39,016 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 259, in register
    state.register()
  File "/app/states.py", line 18, in register
    self.register_transition(COMPUTE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 570, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 355, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 402, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 07.12.23 13:44:39] [Level: fatal] target state compute not found
2023-12-07 13:44:39,136 WARN exited: app (exit status 1; not expected)
2023-12-07 13:44:41,153 INFO spawned: 'app' with pid 15
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 259, in register
    state.register()
  File "/app/states.py", line 18, in register
    self.register_transition(COMPUTE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 570, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 355, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 402, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 07.12.23 13:44:41] [Level: fatal] target state compute not found
2023-12-07 13:44:41,274 WARN exited: app (exit status 1; not expected)
2023-12-07 13:44:44,300 INFO spawned: 'app' with pid 17
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 259, in register
    state.register()
  File "/app/states.py", line 18, in register
    self.register_transition(COMPUTE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 570, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 355, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 402, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 07.12.23 13:44:44] [Level: fatal] target state compute not found
2023-12-07 13:44:44,433 WARN exited: app (exit status 1; not expected)
2023-12-07 13:44:45,438 INFO gave up: app entered FATAL state, too many start retries too quickly
