2023-12-19 20:02:38,241 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-12-19 20:02:38,242 INFO supervisord started with pid 7
2023-12-19 20:02:39,246 INFO spawned: 'app' with pid 8
2023-12-19 20:02:39,248 INFO spawned: 'nginx' with pid 9
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 310, in register
    state.register()
  File "/app/states.py", line 20, in register
    self.register_transition(WRITE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 590, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 446, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 494, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 19.12.23 20:02:39] [Level: fatal] target state write not found
2023-12-19 20:02:39,821 WARN exited: app (exit status 1; not expected)
2023-12-19 20:02:40,827 INFO spawned: 'app' with pid 15
2023-12-19 20:02:40,829 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 310, in register
    state.register()
  File "/app/states.py", line 20, in register
    self.register_transition(WRITE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 590, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 446, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 494, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 19.12.23 20:02:41] [Level: fatal] target state write not found
2023-12-19 20:02:41,255 WARN exited: app (exit status 1; not expected)
2023-12-19 20:02:43,269 INFO spawned: 'app' with pid 19
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 310, in register
    state.register()
  File "/app/states.py", line 20, in register
    self.register_transition(WRITE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 590, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 446, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 494, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 19.12.23 20:02:43] [Level: fatal] target state write not found
2023-12-19 20:02:43,700 WARN exited: app (exit status 1; not expected)
2023-12-19 20:02:46,715 INFO spawned: 'app' with pid 23
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 310, in register
    state.register()
  File "/app/states.py", line 20, in register
    self.register_transition(WRITE_STATE)  
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 590, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator, label)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 446, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/root/.local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 494, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 19.12.23 20:02:47] [Level: fatal] target state write not found
2023-12-19 20:02:47,146 WARN exited: app (exit status 1; not expected)
2023-12-19 20:02:48,149 INFO gave up: app entered FATAL state, too many start retries too quickly
